Repository mlr-org/mlr3pipelines, pull requests merged in 2020-04, with the labels that each got.

#378 Update docs, fixes #370
  R/PipeOpClassBalancing.R
  man/mlr_pipeops_classbalancing.Rd
Labels: Status: Completed, Type: Documentation

#349 first PipeOpProxy draft
  DESCRIPTION
  NAMESPACE
  R/PipeOpBranch.R
  R/PipeOpProxy.R
  attic/experiments.R
  man/PipeOp.Rd
  man/PipeOpEnsemble.Rd
  man/PipeOpImpute.Rd
  man/PipeOpProxy.Rd
  man/PipeOpTaskPreproc.Rd
  man/mlr_pipeops.Rd
  man/mlr_pipeops_boxcox.Rd
  man/mlr_pipeops_branch.Rd
  man/mlr_pipeops_chunk.Rd
  man/mlr_pipeops_classbalancing.Rd
  man/mlr_pipeops_classifavg.Rd
  man/mlr_pipeops_classweights.Rd
  man/mlr_pipeops_colapply.Rd
  man/mlr_pipeops_collapsefactors.Rd
  man/mlr_pipeops_copy.Rd
  man/mlr_pipeops_datefeatures.Rd
  man/mlr_pipeops_encode.Rd
  man/mlr_pipeops_encodeimpact.Rd
  man/mlr_pipeops_encodelmer.Rd
  man/mlr_pipeops_featureunion.Rd
  man/mlr_pipeops_filter.Rd
  man/mlr_pipeops_fixfactors.Rd
  man/mlr_pipeops_histbin.Rd
  man/mlr_pipeops_ica.Rd
  man/mlr_pipeops_imputehist.Rd
  man/mlr_pipeops_imputemean.Rd
  man/mlr_pipeops_imputemedian.Rd
  man/mlr_pipeops_imputemode.Rd
  man/mlr_pipeops_imputenewlvl.Rd
  man/mlr_pipeops_imputesample.Rd
  man/mlr_pipeops_kernelpca.Rd
  man/mlr_pipeops_learner.Rd
  man/mlr_pipeops_missind.Rd
  man/mlr_pipeops_modelmatrix.Rd
  man/mlr_pipeops_mutate.Rd
  man/mlr_pipeops_nop.Rd
  man/mlr_pipeops_pca.Rd
  man/mlr_pipeops_quantilebin.Rd
  man/mlr_pipeops_regravg.Rd
  man/mlr_pipeops_removeconstants.Rd
  man/mlr_pipeops_scale.Rd
  man/mlr_pipeops_scalemaxabs.Rd
  man/mlr_pipeops_scalerange.Rd
  man/mlr_pipeops_select.Rd
  man/mlr_pipeops_smote.Rd
  man/mlr_pipeops_spatialsign.Rd
  man/mlr_pipeops_subsample.Rd
  man/mlr_pipeops_threshold.Rd
  man/mlr_pipeops_unbranch.Rd
  man/mlr_pipeops_yeojohnson.Rd
  tests/testthat/test_pipeop_proxy.R
Labels: Status: Completed

#278 remove $set_col_role, deprecated
  R/PipeOpClassWeights.R
  R/PipeOpTaskPreproc.R
  tests/testthat/helper_functions.R
  tests/testthat/test_pipeop_featureunion.R
Labels: Status: Completed

#365 Initial draft for count vectorizer
  DESCRIPTION
  NAMESPACE
  R/PipeOpTextVectorizer.R
  R/utils.R
  man/PipeOp.Rd
  man/PipeOpEnsemble.Rd
  man/PipeOpImpute.Rd
  man/PipeOpProxy.Rd
  man/PipeOpTaskPreproc.Rd
  man/mlr_pipeops.Rd
  man/mlr_pipeops_boxcox.Rd
  man/mlr_pipeops_branch.Rd
  man/mlr_pipeops_chunk.Rd
  man/mlr_pipeops_classbalancing.Rd
  man/mlr_pipeops_classifavg.Rd
  man/mlr_pipeops_classweights.Rd
  man/mlr_pipeops_colapply.Rd
  man/mlr_pipeops_collapsefactors.Rd
  man/mlr_pipeops_copy.Rd
  man/mlr_pipeops_datefeatures.Rd
  man/mlr_pipeops_encode.Rd
  man/mlr_pipeops_encodeimpact.Rd
  man/mlr_pipeops_encodelmer.Rd
  man/mlr_pipeops_featureunion.Rd
  man/mlr_pipeops_filter.Rd
  man/mlr_pipeops_fixfactors.Rd
  man/mlr_pipeops_histbin.Rd
  man/mlr_pipeops_ica.Rd
  man/mlr_pipeops_imputehist.Rd
  man/mlr_pipeops_imputemean.Rd
  man/mlr_pipeops_imputemedian.Rd
  man/mlr_pipeops_imputemode.Rd
  man/mlr_pipeops_imputenewlvl.Rd
  man/mlr_pipeops_imputesample.Rd
  man/mlr_pipeops_kernelpca.Rd
  man/mlr_pipeops_learner.Rd
  man/mlr_pipeops_missind.Rd
  man/mlr_pipeops_modelmatrix.Rd
  man/mlr_pipeops_mutate.Rd
  man/mlr_pipeops_nop.Rd
  man/mlr_pipeops_pca.Rd
  man/mlr_pipeops_quantilebin.Rd
  man/mlr_pipeops_regravg.Rd
  man/mlr_pipeops_removeconstants.Rd
  man/mlr_pipeops_scale.Rd
  man/mlr_pipeops_scalemaxabs.Rd
  man/mlr_pipeops_scalerange.Rd
  man/mlr_pipeops_select.Rd
  man/mlr_pipeops_smote.Rd
  man/mlr_pipeops_spatialsign.Rd
  man/mlr_pipeops_subsample.Rd
  man/mlr_pipeops_textvectorizer.Rd
  man/mlr_pipeops_threshold.Rd
  man/mlr_pipeops_unbranch.Rd
  man/mlr_pipeops_yeojohnson.Rd
  tests/testthat/test_pipeop_textvectorizer.R
Labels: Status: Completed, Status: Review Needed

#371 use only mlr3 task_types to set the task and prediction types
  R/PipeOpLearner.R
  R/PipeOpLearnerCV.R
Labels: Status: Completed

#372 Pipeop histbin prevent NAs for numerics that are out of range of training data
  R/PipeOpHistBin.R
  man/mlr_pipeops_histbin.Rd
  man/mlr_pipeops_textvectorizer.Rd
  tests/testthat/test_pipeop_histbin.R
Labels: Status: Completed, Status: Review Needed

#374 Pipeop learner and learnercv if a Graph and no id is used, collapse the ids of the Graph
  R/PipeOpLearner.R
  R/PipeOpLearnerCV.R
  man/mlr_pipeops_learner.Rd
  man/mlr_pipeops_learner_cv.Rd
  tests/testthat/test_pipeop_learner.R
  tests/testthat/test_pipeop_learnercv.R
Labels: Status: Completed, Status: Review Needed
